services:

  frontend:
    build: ./frontend
    networks:
      - app-network

  backend:
    build: ./backend
    networks:
      - app-network
    volumes:
      - ./media:/app/media
    
  nginx:
    build: ./nginx
    ports:
      - "8080:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./media:/etc/nginx/media

networks:
  app-network:
    driver: bridge